INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Ahuntsic Public Library', 1, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Ahuntsic Public Library', 2, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Belleville Public Library', 1, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Belleville Public Library', 2, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 1, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 2, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 3, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 4, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 5, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 7, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 8, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 9, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 10, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 11, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 12, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 13, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 14, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Benny Public Library', 15, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 2, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 4, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 5, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 6, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 7, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 8, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 9, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 10, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 11, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 12, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 13, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 14, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 15, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 16, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 17, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 18, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Biblio-courrier Public Library', 19, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque de la Maison culturelle et communautaire Public Library', 1, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque de la Maison culturelle et communautaire Public Library', 2, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque de la Maison culturelle et communautaire Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque de la Maison culturelle et communautaire Public Library', 4, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 1, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 2, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 3, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 4, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 6, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 7, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 8, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 9, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 10, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 11, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 12, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 13, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 14, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 15, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 16, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 17, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 18, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Bibliothèque interculturelle Public Library', 19, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 3, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 4, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 5, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 6, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 7, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 8, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 9, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 10, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 11, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 12, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 13, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 14, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 15, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 16, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 17, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Cartierville Public Library', 18, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 1, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 2, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 4, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 5, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Charleroi Public Library', 6, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 2, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 3, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 4, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 5, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 7, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 8, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 9, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 10, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 11, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 12, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 13, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 14, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 15, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 16, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 17, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Côte-des-Neiges Public Library', 18, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 1, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 2, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 3, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 4, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 5, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 6, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 7, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 8, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 9, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 10, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Du Boisé Public Library', 11, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 2, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 3, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 4, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 6, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 7, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 8, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Frontenac Public Library', 9, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 2, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 3, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 4, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 5, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 6, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Georges-Vanier Public Library', 7, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 2, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 3, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 4, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 5, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Haut-Anjou Public Library', 6, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 1, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 2, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 3, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 4, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 5, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Henri-Bourassa Public Library', 7, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Hochelaga Public Library', 1, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Hochelaga Public Library', 2, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Hochelaga Public Library', 3, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Hochelaga Public Library', 4, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Hochelaga Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Île des Sœurs Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Île des Sœurs Public Library', 2, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Île des Sœurs Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Île des Sœurs Public Library', 4, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Île des Sœurs Public Library', 5, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jean-Corbeil Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 1, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 2, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 3, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 4, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 5, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 7, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 8, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 9, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 10, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 11, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 12, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 13, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 14, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 15, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 16, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Langelier Public Library', 17, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('La Petite-Patrie Public Library', 1, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('La Petite-Patrie Public Library', 2, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('La Petite-Patrie Public Library', 3, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('La Petite-Patrie Public Library', 4, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('La Petite-Patrie Public Library', 5, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Le Prévost Public Library', 1, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 1, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 2, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 3, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 4, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 5, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 6, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 7, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 8, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L''Île-Bizard Public Library', 9, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 1, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 2, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 3, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 4, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 5, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 7, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 8, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 9, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 10, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 11, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 12, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 13, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 14, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('L’Octogone (LaSalle) Public Library', 15, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Maisonneuve Public Library', 1, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Maisonneuve Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Maisonneuve Public Library', 3, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 2, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 3, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 4, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 5, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 6, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 7, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 8, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marc-Favreau Public Library', 9, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marie-Uguay Public Library', 1, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marie-Uguay Public Library', 2, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Marie-Uguay Public Library', 3, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Mercier Public Library', 1, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Mercier Public Library', 2, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Mercier Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Mercier Public Library', 4, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Mordecai-Richler Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 1, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 2, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 3, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 4, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 6, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Parc-Extension Public Library', 7, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 2, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 3, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 4, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 5, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Père-Ambroise Public Library', 6, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 1, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 2, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 3, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 4, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 5, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 6, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 7, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 8, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 9, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 10, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 11, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 12, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 13, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 14, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pierrefonds Public Library', 15, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 2, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 3, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 4, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 5, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 6, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 7, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Plateau-Mont-Royal Public Library', 8, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 2, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 3, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 4, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 6, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 7, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 8, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 9, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Pointe-aux-Trembles Public Library', 10, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 1, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 2, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 4, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 5, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 6, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 7, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 8, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 9, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 10, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 11, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rivière-des-Prairies Public Library', 12, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 1, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 2, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 3, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 4, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 5, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 6, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 7, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Robert-Bourassa Public Library', 8, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 1, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 2, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 3, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 4, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 5, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 6, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 7, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 8, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 9, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 10, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 11, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 12, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 13, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 14, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 15, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 16, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 17, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 18, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Rosemont Public Library', 19, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Roxboro Public Library', 1, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Roxboro Public Library', 2, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Roxboro Public Library', 3, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Roxboro Public Library', 4, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Roxboro Public Library', 5, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 1, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 2, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 3, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 4, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 5, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 6, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 7, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 8, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 9, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 10, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 11, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 12, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 13, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 14, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 15, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 16, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 17, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 18, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 19, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Charles Public Library', 20, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 1, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 3, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 4, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 5, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 6, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 7, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 8, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 9, 0, 4, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Henri Public Library', 10, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Léonard Public Library', 1, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Michel Public Library', 1, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Michel Public Library', 2, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Michel Public Library', 3, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 1, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 3, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 4, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 5, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 6, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 7, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 8, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 9, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 10, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 11, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 12, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 13, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 14, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saint-Pierre Public Library', 15, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 1, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 2, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 3, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 4, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 5, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 6, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 7, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 8, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 9, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 10, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Salaberry Public Library', 11, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saul-Bellow Public Library', 1, 0, 2, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Saul-Bellow Public Library', 2, 0, 2, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 1, 0, 5, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 3, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 4, 0, 4, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 5, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Jacqueline-De Repentigny Public Library', 6, 0, 1, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 1, 0, 3, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 2, 0, 6, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 3, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 4, 0, 3, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 5, 0, 5, false);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 6, 0, 1, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 7, 0, 6, true);
INSERT INTO room (branch, roomno, status, capacity, haswhiteboard) VALUES ('Vieux-Saint-Laurent Public Library', 8, 0, 3, true);